# Generated by Django 5.1.2 on 2025-06-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orden_nota_itemorden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='itemorden',
            old_name='producto',
            new_name='product',
        ),
    ]
